# Write your MySQL query statement below
SELECT U.USER_ID , ROUND(AVG(IF(C.ACTION ='CONFIRMED',1,0)),2) AS 'CONFIRMATION_RATE'
FROM SIGNUPS U
LEFT JOIN CONFIRMATIONS C 
ON U.USER_ID = C.USER_ID
GROUP BY U.USER_ID;


