-- WITH MANAGER AS(
--     SELECT REPORTS_TO, COUNT(*) AS X,
--     ROUND(AVG(AGE)) AS AVERAGE_AGE 
--     FROM EMPLOYEES 
--     GROUP BY REPORTS_TO
-- )
-- SELECT E.EMPLOYEE_ID, E.NAME, M.X AS REPORTS_COUNT,M.AVERAGE_AGE
-- FROM EMPLOYEES E
-- JOIN MANAGER M
-- ON E.EMPLOYEE_ID = M.REPORTS_TO
-- ORDER BY E.EMPLOYEE_ID;


SELECT  E1.EMPLOYEE_ID, E1.NAME, COUNT(E2.REPORTS_TO) AS REPORTS_COUNT, 
ROUND(AVG(E2.AGE)) AS AVERAGE_AGE
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.REPORTS_TO
GROUP BY E1.EMPLOYEE_ID
ORDER BY  E1.EMPLOYEE_ID

