# Write your MySQL query statement below
-- SELECT(
-- SELECT DISTINCT(SALARY) AS SECONDHIGHESTSALARY
-- FROM EMPLOYEE 
-- ORDER BY SALARY DESC
-- LIMIT 1 OFFSET 1) AS SECONDHIGHESTSALARY;

SELECT MAX(SALARY) AS SECONDHIGHESTSALARY
FROM EMPLOYEE
WHERE SALARY< (SELECT MAX(SALARY) FROM EMPLOYEE);